[package]
edition = "2021"
name = "_ch_rust_prql"
version = "0.1.0"

[dependencies]
prqlc = "0.11.3"
serde_json = "1.0"

[lib]
crate-type = ["staticlib"]

[profile.release]
debug = false

[profile.release-thinlto]
inherits = "release"
lto = true
